 ; Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

; By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

(def fib-vec (atom )

(defn fibonacci [limit] 
  (loop [y 1
         z 2]
    (swap! fib-vec (conj fib-vec z)) 
      (if (> limit (count fib-vec))
        (recur z (+ y z))
        fib-vec)))

(let [y 2]
  (conj fib-vec y))

(fibonacci 40)

(reduce + (filter even? (fibonacci 400)))

(defn fib2 [x]
  (if (<= x 1)
    x
    (+ (fib2 (- x 1)) (fib2 (- x 2)))))

(do (def expre (fib2 33))(time expre)(print (eval expre)))


(print (+ 1 1))
