; Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

; By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

(def first-pair [1 2])

;; Process:
  ;; next-fib
  ;; iterate next-fib
  ;; take-while < 4000000
  ;; filter even?
  ;; reduce +

(defn next-fib [pair]
  (let [first (nth first-pair (- (count first-pair) 2))
        second (last first-pair)]
    (+ first second)))

(reduce + (filter even? (into (sorted-set) (flatten (take 31 (iterate new-pair [1 2]))))))
